### ISSUE TITLE
IRL Time ?

### ISSUE THREAD

**Issue by mframbou** [gbl/WorldTime#1]
Hey, it's me again, and it's again not an issue x), but could you add an IRL Time just like the World Time with position config ? Cause I got a bad computer so I play in fullscreen, but when I have to left it to check the hour, bruh it's lagging af, so if I could have the IRL time in game it would be perfect, thanks :DD

**Comment by gbl** [comment]
That's actually a nice idea, and I just implemented it and uploaded to CurseForge. Please tell me if it works for you.

**Comment by mframbou** [comment]
Oh i forgot, i'm playing on 1.14 ^^

**Comment by gbl** [comment]
Give me some time, porting that stuff to other versions than the one I'm "currently" working with takes a bit .. 1.14 Version is on curseforge, just a matter of time when it's approved now.
