### ISSUE TITLE
Specific day count option

### ISSUE THREAD

**Issue by Gallucky** [gbl/WorldTime#11]
I have a suggestion to make and it is the idea of the game time but additional to just show the date number. For example:
If someone's world is in day 1000, you can't use the java simple date format to display day 1000, only the day number according to the year or a month.
So, my suggestion is that you can put days played (day counter) similar to the Game Time option.
Many thanks for considering my request.

**Comment by gbl** [comment]
You can already do that, a J displays the in-world day number, as an extension to the SimpleDateFormat letters.

**Comment by Gallucky** [comment]
Thank you I didn't know that there is an extension for that
