### ISSUE TITLE
World time on new worlds starts at 6:00

### ISSUE THREAD

**Issue by leoiswho** [gbl/WorldTime#12]
I am using the 1.19.2 version on the Fabric mod launcher and when I start a new world with this mod or run the command "/timeset 0" the wold timer starts counting from 6 (six minutes.)

Also when I try to change the time format it won't save my adjustments. (I tried putting hh:mm:ss in the world time to get Hours:Minutes:Seconds counted.) However, it will save any adjustments to its position.

**Comment by gbl** [comment]
It's not starting at 6 minutes, it's starting at 06:00 in the morning - 6 am. The part after the colon is minutes in world time, not seconds in real time.

Changing the time format works for me. If it doesn't for you, make sure to press the "Done" button, don't use Esc to leave the screen.
