### ISSUE TITLE
Real Time does not account for certain strings

### ISSUE THREAD

**Issue by JuceInUse** [gbl/WorldTime#14]
I wanted my time setup to be "hh:mm:ss.S aa zzzz". For example, this would let you see times like "12:41:37.9 PM Pacific Standard Time". However, whenever doing this, it automatically used the millisecond down to the thousandth rather than to the tenth as I had specified
![image](https://user-images.githubusercontent.com/85078618/194685750-ffa2195a-1280-428f-8f5e-6348c49abb8a.png)

![image](https://user-images.githubusercontent.com/85078618/194685735-66f0e661-b659-466a-ad59-76e649a793f9.png)

EDIT: Just to specify, yes I am aware that this is how Javascript would work so this is technically more of an enhancement question, but it would be really nice to not have such a spastic millisecond counter lol

**Comment by JuceInUse** [comment]
Also, and I know this is also just enhancement, it would be nice if you could denote custom new lines! Not sure if that would be really hard to add, I just want a line for the date haha

**Comment by gbl** [comment]
Sorry, but I'm using Java's SimpleDateFormat class. Your suggestion would basically mean rebuilding that class, which is way too much work, especially to test and get right. So, sorry, but no changes to how that works.
