### ISSUE TITLE
Mod not Configurable

### ISSUE THREAD

**Issue by callmekargen** [gbl/WorldTime#16]
in the 1.20 version of the mod there is no way to configure the mod in game despite what you say what to do, i'm sure if it's something i'm doing wrong. If you can help me that would be appreciated thanks.

**Comment by gbl** [comment]
yes that's right, the config system doesn't work with 1.19.4. or 1.20 because Mojang changed a lot about how screen and GUIs work. In order to update the mod at all, I removed the config part. You can still edit the json manually, or use an older version (<= 1.19.3) to use the GUI config.
