### ISSUE TITLE
Add user location

### ISSUE THREAD

**Issue by JoCat** [gbl/WorldTime#2]
Hello. I tried to add the output of the user's location in the game, but ran into all sorts of errors.
Everything rests on the absence of the `mcversion-1.15.properties` file.

If possible, can you publish this file, or integrate functionality for displaying user coordinates from my fork into your mod?

I am using Minecraft version 1.15.

**Comment by JoCat** [comment]
I tried to use the modules of the +/- latest versions, but failed, the game only started on a test bench. On other builds, the game crashed.
I also tried to get module versions from [this commit](https://github.com/gbl/WorldTime/commit/75768909e09a0af10ba7d38cdec4091ec8dcbf43), but also failed. The game crashes when i clicked on the Mod Menu button.

**Comment by gbl** [comment]
Yes you're right, moving the properties files outside the source tree makes it hard for people to rebuild the mod. I did that to make it easier to share version files between my mods, but outside the project itself isn't the right way to do this.
I added the property files back in, so if you merge my lastest commit into yours you should be able to compile.
I didn't add the player location because other mods, like voxelmap, are doing this well, but feel free to keep your fork or publish it yourself!

**Comment by JoCat** [comment]
Thank you, I also watched various modifications that display the player’s coordinates, but they didn’t suit me for various reasons (on our game server we specifically refused minimap). And your mod came up very well, so the choice fell on him))

**Comment by JoCat** [comment]
Hello. I tried load you properties file, but failed))
if i use gbfabrictools_version=1.2.0 get error:
```
error: cannot find symbol
        config.forget("X Percent");
              ^
  symbol:   method forget(String)
  location: variable config of type Configuration
```
~~if i use gbfabrictools_version=1.2.1.1.15 mod will be successfully built, but when the test starts, the game crashes with the following error:~~ error fixed

**Comment by gbl** [comment]
Is the gbfabrictools 1.2.1 error fixed? It seems so from the strikethrough in the comment.

If not, you can use 1.2.0 version of the tools as well, and remove the forget() calls. The old version of WorldTime had some config entries that are outdated; forget() removes them from the config for people who update. If you never used an old config, the forget() calls are pointless.

**Comment by JoCat** [comment]
yes in gbfabrictools 1.2.1 no error

**Comment by JoCat** [comment]
I caught a couple more errors, but all of them were due to the fact that I changed archivesBaseName in build.gradle.
maybe the error that I threw above was also somehow connected with this xD

**Comment by JoCat** [comment]
thanks for the help, if you want, you can use the functionality from my fork :)
