### ISSUE TITLE
[Forge 1.16.1] Incorrect Forge Compatibility Indicator on Multiplayer Menu

### ISSUE THREAD

**Issue by jdawg3636** [gbl/WorldTime#5]
Minecraft Version: 1.16.1
Forge Version: 32.0.106
WorldTime Version: worldtime-1.16.1-forge32.0.38-1.2.2.jar

The mod crashes when run on a dedicated server. This seemed fine at first (though it would be nice if this wasn't the case) as all of the mod's functionality is on the client side.

Removing the mod from the server resolves this, but unfortunately it causes the client to think that the server is incompatible and to display a red "X" next to the server's listing in the multiplayer menu which displays the warning "Incompatible FML modded server: Server mod list is not compatible" when hovered over. The issue is purely visual and does not actually prevent the user from joining.

My guess is that DISPLAYTEST is not being overriden as recommended in the Forge Documentation (https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods), but as far as I can tell this repo only contains source files for the Fabric versions so I can't be sure.

**Comment by gbl** [comment]
This should be fixed in the new version (1.2.3). Source code is pushed to GH now as well, in its own branch.
